# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

download:
  url:   /download/:filename
  param: { module: download, action: index }
  requirements: { filename: .+ }

index:
  url:    /settings
  param:  { module: settings, action: index }

add_new:
  url:    /settings/add-new
  param:  { module: settings, action: add }

groups:
  url:    /settings/groups
  param:  { module: groups, action: index }
  
groups_edit:
  url:    /settings/groups/edit/*
  param:  { module: groups, action: edit }

groups_get_freq:
  url:    /settings/groups/get-freq
  param:  { module: groups, action: getFrequency }

groups_new:
  url:    /settings/groups/new
  param:  { module: groups, action: new }

files:
  url:    /settings/files
  param:  { module: files, action: index }

files_edit:
  url:    /settings/files/edit/*
  param:  { module: files, action: edit }

files_new:
  url:    /settings/files/new
  param:  { module: files, action: new }

file:
  url:    /settings/file/:fileId
  param:  { module: settings, action: file }
  requirements: { fileId: \d+ }

# default rules
homepage:
  url:    /
  param:  { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:    /:module
  param:  { action: index }

default:
  url:    /:module/:action/*
