<?php



/**
 * Skeleton subclass for performing query and update operations on the 'download_log' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Sun Jun 19 19:03:28 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class DownloadLogQuery extends BaseDownloadLogQuery {

} // DownloadLogQuery
