<?php


/**
 * Skeleton subclass for representing a row from the 'download_log' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Jun 19 18:55:17 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DownloadLog extends BaseDownloadLog {

} // DownloadLog
